# Generated by Django 3.0.5 on 2020-11-13 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fechas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UDI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udi', models.FloatField()),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Fechas')),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolar', models.CharField(max_length=50)),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Fechas')),
            ],
        ),
    ]
