# Generated by Django 3.0.5 on 2020-11-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='udi',
            name='tipo',
            field=models.CharField(default='porciento anual', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moneda',
            name='dolar',
            field=models.FloatField(),
        ),
    ]
