# Generated by Django 3.0.5 on 2020-11-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201113_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneda',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='udi',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Fechas',
        ),
    ]
